Aris3.0Fe/Controllers/FilmController.cs
using Aris3._0.Infrastructure.Data.Context;
using Aris3._0Fe.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using System.Net;
using System.Text;
namespace Aris3._0Fe.Controllers
{
    public class FilmController : Controller
    {
        private readonly ArisDbContext dbContext;

        public FilmController(ArisDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index(string id, string posterurl, string name, string original_name, string thumburl)
        {
            var episodeArray= new List<Episode>();

            if (id != null)
            {
                var film = dbContext.Films.FirstOrDefault(f => f.Id == id);
                if (film != null)
                {
                    film.View += 1;
                    dbContext.SaveChanges();
                }

                episodeArray = dbContext.Episodes.Where(e=>e.Server.Film.Id == id)
                                 .Include(s => s.Server)
                                     .ThenInclude(s => s.Film)
                                      .ThenInclude(f=>f.Countries)
                                 .Include(s => s.Server)
                                     .ThenInclude(s => s.Film)
                                      .ThenInclude(f => f.Categories)
                                .Include(s => s.Server)
                                     .ThenInclude(s => s.Film)
                                      .ThenInclude(f => f.Countries)
                                .Include(s => s.Server)
                                     .ThenInclude(s => s.Film)
                                      .ThenInclude(f => f.Actors)
                                 .ToList();
            }

            return View(episodeArray);
        }



        [HttpGet]
        public async Task<IActionResult> Search(string searchQuery, Guid id,string category)
        {
            if (searchQuery != null && id == Guid.Empty)
            {
                string RemoveDiacritics(string text)
                {
                    if (string.IsNullOrEmpty(text)) return text;
                    var normalized = text.Normalize(NormalizationForm.FormD);
                    var sb = new StringBuilder();
                    foreach (var c in normalized)
                    {
                        if (CharUnicodeInfo.GetUnicodeCategory(c) != UnicodeCategory.NonSpacingMark)
                            sb.Append(c);
                    }
                    return sb.ToString().Normalize(NormalizationForm.FormC).ToLower();
                }

                List<Film> films = await dbContext.Films.ToListAsync();

                List<Film> key;

                if (!string.IsNullOrWhiteSpace(searchQuery) && searchQuery.Length >= 3)
                {
                    string keywordStart = RemoveDiacritics(searchQuery.Substring(0, 3));

                    key = films.Where(f => !string.IsNullOrEmpty(f.Name) &&
                                           RemoveDiacritics(f.Name).StartsWith(keywordStart))
                               .ToList();

                    if (key.Count >= 1)
                    {
                        ViewBag.Count = key.Count;
                        ViewBag.TuKhoa = searchQuery;
                        return View(key);
                    }
                }
                else
                {
                    key = films;
                    ViewBag.Count = key.Count;
                    ViewBag.TuKhoa = searchQuery;
                    return View(key);
                }

                return NotFound("Không tìm thấy phim.");
            }
            else if (string.IsNullOrWhiteSpace(searchQuery) && id == Guid.Empty && !string.IsNullOrEmpty(category))
            {
                var decodedCategory = WebUtility.UrlDecode(category).Trim();

                var films = await dbContext.Films
                                           .Include(f => f.Categories)
                                           .Where(f => f.Categories.Any(c => c.Name.ToLower() == decodedCategory.ToLower()))
                                           .ToListAsync();
                var cate = dbContext.categories
                                    .FirstOrDefault(c => c.Name.ToLower() == decodedCategory.ToLower());
                ViewBag.Country = cate?.Name;
                return View(films);
            }
            else
            {
                var films = await dbContext.Films
                                           .Include(f => f.Countries)
                                           .Where(f => f.Countries.Any(c => c.Id == id))
                                           .ToListAsync();

                var cotry = dbContext.Countries.FirstOrDefault(c => c.Id == id);
                ViewBag.Country = cotry?.Name;
                return View(films);
            }
        }
    }
}

Aris3.0Fe/Controllers/HomeController.cs
using Aris3._0.Infrastructure.Data.Context;
using Aris3._0Fe.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Diagnostics;
using System.Net.Http;

namespace Aris3._0Fe.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ArisDbContext dbContext;
        private readonly HttpClient _httpClient;
        public HomeController(ILogger<HomeController> logger, IHttpClientFactory httpClientFactory,ArisDbContext dbContext)
        {
            _httpClient = httpClientFactory.CreateClient();
            _logger = logger;
            this.dbContext = dbContext;
        }
        [Authorize]
        public IActionResult Index()
        {
            var listFilm = dbContext.Films.ToList();
            _logger.LogInformation("Films count: {Count}", listFilm.Count);
            ViewBag.FilmList = listFilm;
            return View(listFilm);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        [HttpPost]
        public async Task<IActionResult> GetAllFilmToDb()
        {
            var response = await _httpClient.PostAsync("https://localhost:7248/api/film/3", null);

            var resultJson = await response.Content.ReadAsStringAsync();

            return RedirectToAction("Index");
        }
    }
}

Aris3.0Fe/Views/Home/Index.cshtml
@model List<Film>

@{
    ViewData["Title"] = "Home Page";
}

<div class="hero-section d-flex align-items-end">
    <div class="media-title">
        <div class="film-type d-flex flex-row align-items-center gap-3">
            <h2 class="split-text">A</h2>
            <h4 id="logo-film-style"style="color:darkgray">Aris Series</h4>
        </div>
        <h1 class="film-name" id="film-name" style="font-family:roboto;font-weight:bolder;font-size:50px"></h1>
        <div class="ranking-infor">
            <div class="film-ranking" style="color:black">
                <div class="rank" style="font-size:12px;font-weight:bolder">Top</div>
                <div class="rank-number" style="font-weight:bolder">1</div>
            </div>
            <h4>#1 Tv Shows Today</h4>
        </div>
        <div class="film-content" id="film-content" style="font-family:roboto;font-weight:bold"></div>
        <div class="button-group d-flex flex-row align-items-center gap-2">
            <a id="play-button" class="btn btn-play">
                <i class="bi bi-play-fill"></i>
                <h5 style="font-family:roboto;font-weight:800">Watch</h5>
            </a>
            <div class="button-group-2">
                <button class="btn-love">
                    <i class="bi bi-suit-heart-fill"></i>
                </button>
                <button class="btn-infor">
                    <i class="bi bi-info-circle-fill"></i>
                </button>
            </div>
        </div>
    </div>
</div>


<script>
    const films = @Html.Raw(Json.Serialize(Model));
    console.log(films);
    let index = films.length-1;

    function showFilm(i) {
        if (!films[i]) return;
        document.getElementById('film-name').textContent = films[i].name;

        let content = films[i].content || '';
        content = content.replace(/["']/g, '').trim();
        const maxLength = 400;
        if (content.length > maxLength) {
            content = content.substring(0, maxLength).trim() + '...';
        }
        document.getElementById('film-content').textContent = content;

        document.getElementById('play-button').href = '@Url.Action("Index", "Film")?id=' + encodeURIComponent(films[i].id);
        const logo = document.getElementById('logo-film-style');
        if (films[i].type && films[i].type.toLowerCase() === "movie") {
            logo.textContent = "Aris Movies";
        } else if (films[i].type && films[i].type.toLowerCase() === "series") {
            logo.textContent = "Aris Series";
        } else {
            logo.textContent = "Aris Cartoon";
        }
    }

    showFilm(index);

    setInterval(() => {
        index = (index - 1) % films.length;
        showFilm(index);
    }, 600000); 
</script>